name: assignment_1_scratch
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.3
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pandas
  - scikit-learn
  - opencv
  - pip:
    - torcheval
    - click
    - matplotlib